services:
  airflow:
    image: apache/airflow:2.9.2
    ports:
      - "8080:8080" 
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
    volumes:
      # Gunakan 'named volume' untuk folder utama agar SQLite tidak error di Windows
      - airflow_data:/opt/airflow
      # Tetap mapping folder dags agar Anda bisa simpan file kodingan dari Windows
      - ./dags:/opt/airflow/dags 
    command: >
      bash -c "rm -f /opt/airflow/airflow-webserver.pid && airflow standalone"

volumes:
  airflow_data: